### ISSUE TITLE
warning from blead with gcc

### ISSUE THREAD

**Issue by jhi** [rjbs/Time-Piece#15]
Piece.xs:1037:29: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]

sizeof() is unsigned, so it should be cast to (int).

**Comment by smith153** [comment]
Thanks for the report. I might be able to change len to unsigned itself. Man pages states lowest value returned from strftime() is 0.

**Comment by jhi** [comment]
On Tuesday-201506-09 9:51, Samuel Smith wrote:
> Thanks for the report. I might be able to change len to unsigned itself.
> Man pages states lowest value returned from strftime() is 0.

Or, rather, it's a size_t, which is unsigned.

http://www.cplusplus.com/reference/ctime/strftime/

**Comment by smith153** [comment]
Changed to size_t in 1.31.
