### ISSUE TITLE
fix_win32_tzenv/putenv causes memory corruption on old MS libcs

### ISSUE THREAD

**Issue by bulk88** [rjbs/Time-Piece#16]
this is a tracking ticket for https://rt.perl.org/Ticket/Display.html?id=125529

if nothing comes of that ticket, here is a patch (rename the .gif to .patch) to fix T::P

![0001-fix-perl-125529-putenv-mem-corruption-on-older-ms-cr patch](https://cloud.githubusercontent.com/assets/997168/8512351/49c8a15e-230c-11e5-8723-68a55aec3752.gif)

**Comment by smith153** [comment]
Thanks, I will look it over.

**Comment by tonycoz** [comment]
The patch attached to the rt.perl.org ticket makes sense to me.

Unfortunately the patch link above doesn't work for me, even if I s/gif$/patch/ (403 error)

**Comment by bulk88** [comment]
Download the gif to disk first, change the file name (not url) .gif to .patch. The rt.perl.org patch is identical to the one here. Github has no attachment feature except gist, and that is a paste tool, so messing with file extensions like its 1999 and geocities is the only way to do it.

**Comment by smith153** [comment]
Pushed out as 1.30_01, please test.
